<?php

namespace App\Exports;


use Maatwebsite\Excel\Concerns\FromCollection;
use DB;
class Ventas_export implements FromCollection
{
    /**
    * @return \Illuminate\Support\Collection
    */

    public function headings()
    {
        return array(
            "usuario_detalle_nombre",
                "equipo_descripcion",
                "equipo_placa",
                "equipo_tipo",
                "checklist_id",     
                "checklis_usuario_id",
                "checklist_equipo" ,
                "checklist_fecha_hora" ,
                "checklist_kilom_inicial" ,
                "checklist_kilom_final" ,
                "checklist_turno" ,
                "checklist_autorizado" ,
                "checklist_usuario_id_autoriza",
                "checklist_estado",
                "check_1" ,
                "check_2" ,
                "check_3" ,
                "check_4" ,
                "check_5" ,
                "check_6" ,
                "check_7" ,
                "check_8" ,
                "check_9" ,
                "check_10" ,
                "check_11" ,
                "check_12" ,
                "check_13" ,
                "check_14" ,
                "check_15" ,
                "check_16" ,
                "check_17" ,
                "check_18" ,
                "check_19" ,
                "check_20" ,
                "check_21" ,
                "check_22",
                "check_23",
                "check_24",
                "check_25",
                "check_26",
                "check_27",
                "check_28",
                "check_29",
                "check_30",
                "check_31",
                "check_32",
                "check_33",
                "check_34",
                "check_35",
                "check_36",
                "check_37",
                "check_38",
                "check_39",
                "check_40",
                "check_41",
                "check_42",
                "check_43",
                "check_44",
                "check_45",
                "check_46",
                "check_47",
                "check_48",
                "check_49",
                "check_50",
                "check_51",
                "check_52",
                "check_53",
                "check_54",
                "check_55",
                "check_56",
                "check_57",
                "check_58",
                "check_59",
                "check_60",
                "check_61",
                "check_62",
                "check_63"
        );
    }
    public function collection()
    {
        $resp=DB::table('checklist')
        ->join('equipos','checklist.checklist_equipo','=','equipos.equipo_id')
        ->join('usuarios','checklist.checklis_usuario_id','=','usuarios.usuario_id')
        ->select(
                "usuarios.usuario_detalle_nombre",
                "equipos.equipo_descripcion",
                "equipos.equipo_placa",
                "equipos.equipo_tipo",
                "checklist.checklist_id",     
                "checklist.checklis_usuario_id",
                "checklist.checklist_equipo" ,
                "checklist.checklist_fecha_hora" ,
                "checklist.checklist_kilom_inicial" ,
                "checklist.checklist_kilom_final" ,
                "checklist.checklist_turno" ,
                "checklist.checklist_autorizado" ,
                "checklist.checklist_usuario_id_autoriza",
                "checklist.checklist_estado",
                "check_1" ,
                "check_2" ,
                "check_3" ,
                "check_4" ,
                "check_5" ,
                "check_6" ,
                "check_7" ,
                "check_8" ,
                "check_9" ,
                "check_10" ,
                "check_11" ,
                "check_12" ,
                "check_13" ,
                "check_14" ,
                "check_15" ,
                "check_16" ,
                "check_17" ,
                "check_18" ,
                "check_19" ,
                "check_20" ,
                "check_21" ,
                "check_22",
                "check_23",
                "check_24",
                "check_25",
                "check_26",
                "check_27",
                "check_28",
                "check_29",
                "check_30",
                "check_31",
                "check_32",
                "check_33",
                "check_34",
                "check_35",
                "check_36",
                "check_37",
                "check_38",
                "check_39",
                "check_40",
                "check_41",
                "check_42",
                "check_43",
                "check_44",
                "check_45",
                "check_46",
                "check_47",
                "check_48",
                "check_49",
                "check_50",
                "check_51",
                "check_52",
                "check_53",
                "check_54",
                "check_55",
                "check_56",
                "check_57",
                "check_58",
                "check_59",
                "check_60",
                "check_61",
                "check_62",
                "check_63" 
                )
        ->orderBy('checklist.checklist_id', 'desc');

        $resp = $resp->get();

        return $resp;
        // return DB::table('ventas')->get();
    }
}
